name: Daily Aare Temperature Email

on:
  schedule:
    - cron: "0 16 * * *" # 16:00 UTC = 18:00 CEST (summer) / 17:00 CET (winter)
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/kejh-z/aare-temp.git .

      - run: node --version && npm install && node index.js
        env:
          RESEND_API_KEY: ${{ secrets.AARE_TEMP }}
